server:
  port: 80
  connectionTimeout: 10000
  connectionRequestTimeout: 10000
  readTimeout: 60000
  maxConnectionIdleTime: 20
  maxConnectionsPerRoute: 200
  maxConnectionsTotal: 200
  servlet:
    context_parameters:
      defaultHtmlEscape: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  max-http-header-size: 24KB

zuul:
  ssl-hostname-validation-enabled: true
  routes:
    open-id-connect:
      path: /o/**
      sensitiveHeaders: Set-Cookie
      url: ${strategic.service.url}/o

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

management:
  # Enable the info and health endpoints
  # A given environment (such as prod) might disable all endpoints,
  # but info and health should still be enabled
  security:
    enabled: false
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info
        
ssl:
  verification:
    enabled: true

spring:
  application:
    name: IDAM Web Public
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

authentication:
  useOAuth2: true
  secureCookie: true

strategic:
  service:
    url: https://idam-api
  endpoint:
    authorize: authenticate
    loginWithPin: pin
    uplift: login/uplift
    forgotPassword: forgotPassword
    resetPassword: resetPassword
    validateResetPasswordToken: validateResetPasswordToken
    users: users
    validateActivationToken: validate
    activation: activate
    userrole: users/{userId}/roles/{roleId}
    search: users
    authorizeOauth2: o/authorize
    selfRegisterUser: users/self
    selfRegistration: users/selfregister
    details: details
    services: services
    health: health

validation:
  password:
    minLength: 8
    maxLength: 256

logging:
  level:
    ROOT: INFO

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey}
