module.exports = {
  WEB_PUBLIC_URL: process.env.TEST_URL,
  IDAM_API: process.env.IDAMAPI,
  SMOKE_TEST_USER_USERNAME: process.env.SMOKE_TEST_USER_USERNAME,
  SMOKE_TEST_USER_PASSWORD: process.env.SMOKE_TEST_USER_PASSWORD
};