java:
  releaseNameOverride: ${SERVICE_NAME}
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  replicas: 1
  environment:
    STRATEGIC_SERVICE_URL: http://idam-api-staging.service.core-compute-aat.internal